### ISSUE TITLE
Discuss design decision of underlying implementation

### ISSUE THREAD

**Issue by tonix-tuft** [donavon/use-event-listener#27]
Currently this tiny useful hook is implemented like this:

``` js
import { useRef, useEffect } from 'react';

const useEventListener = (eventName, handler, element = global) => {
  const savedHandler = useRef();

  useEffect(() => {
    savedHandler.current = handler;
  }, [handler]);

  useEffect(
    () => {
      const isSupported = element && element.addEventListener;
      if (!isSupported) return;

      const eventListener = event => savedHandler.current(event);
      element.addEventListener(eventName, eventListener);
      return () => {
        element.removeEventListener(eventName, eventListener);
      };
    },
    [eventName, element]
  );
};

export default useEventListener;
```

Is `useRef` used for storing `handler` with the idea that `handler` may change **more frequently** than `eventName` or `element` and therefore to avoid removing and re-adding the event listener more frequently?

As I guess, if the hook were implemented like this:

```js
import { useEffect } from 'react';

const useEventListener = (eventName, handler, element = global) => {
  useEffect(
    () => {
      const isSupported = element && element.addEventListener;
      if (!isSupported) return;

      element.addEventListener(eventName, handler);
      return () => {
        element.removeEventListener(eventName, handler);
      };
    },
    [eventName, element, handler]
  );
};

export default useEventListener;

```

Then the following client code:

```js
  ...
  useEventListener('mousemove', ({ clientX, clientY }) => {
    setCoords([clientX, clientY]);
  });
  ...
```

Will cause the event listener to be removed (`useEffect` return function removing the listener called) and re-added on each render, even if `eventName` and `element` do not change.

Whereas, with your implementation and the above client code, the event listener is only removed when either `element` or `eventName`  change, but not when the given `handler` changes on every render...
Meaning that whenever the component using this hook will re-render, only the `useEffect` hook's callback updating the `savedHandler.current` ref will be  executed, and the `useEffect ` hook's callback adding/removing the event listener will not execute.

This also means that using `useCallback` from the client code's side won't add much benefit:

```js
  ...
  // handler never changes, only if setCoords changes...
  const handler = useCallback(
    ({ clientX, clientY }) => {
      setCoords({ x: clientX, y: clientY });
    },
    [setCoords]
  );

  // Passing a memoized handler callback won't add much benefit,
  // it will just avoid executing the `savedHandler.current = handler;` line of the `useEffect` hook
  // within `useEventListener`...
  useEventListener('mousemove', handler);
  ...
```

Are my assumptions and considerations right?

Thanks!

**Comment by srmagura** [comment]
Hey @tonix-tuft, your analysis is correct. Is the hook's current implementation causing any issues? 

We use `useRef` for the reason you said: If a new `handler` is defined on each render, we want to avoid adding and removing the event listener on each render. 

Your implementation would work too. The caller would always need to remember to `useCallback` to prevent lots of unnecessary `addEventListener` / `removeEventListener` calls. The problem is most people (myself included) are not going to remember to `useCallback` every single time.

**Comment by tonix-tuft** [comment]
No no, I was just curious and asked about the design decisions of this hook, no issues. Closing this.

Thank you for your reply!
