### ISSUE TITLE
TypeScript definitions in repo do not match with latest version on npm 

### ISSUE THREAD

**Issue by alexlawrence** [donavon/use-event-listener#28]
## Expected behavior

When installing the latest version of `@use-it/event-listener` from npm, the TypeScript definitions should be the same as in the latest repo version (https://github.com/donavon/use-event-listener/commit/7fd6e56db797944b3621c3d9f99d8efe4ddbca17#diff-88bec6beae84369c0376b56b3bb88fe1).

## Actual behavior

When installing `@use-it/event-listener@0.1.3` from npm, the package contains older TypeScript definitions (https://github.com/donavon/use-event-listener/commit/8494f309e1a2d114d89813c4b7321c19b954151c#diff-88bec6beae84369c0376b56b3bb88fe1). On top of that, it seems to me that they are incorrect. Since the hook uses a native host functionality to subscribe to DOM events, the type for a received should not be `SyntheticEvent`.

## Resolution

Is it possible to release a newer version to npm with the updated TypeScript definitions?

**Comment by srmagura** [comment]
Hey Alex, unfortunately, it has been this way for a while. I've been trying to contact the maintainer, @donavon for around 2 months now. 

I will publish my fork on npm later today. In the meantime, you could use some ugly type assertions to get your code to compile.

**Comment by alexlawrence** [comment]
Thanks for the fast answer @srmagura ! Ah, I didn't know there was an issue with the maintenance of this project. No worries about npm publishing though. For the time being, I simply do a cast to `any`, which gets around the problem.

**Comment by srmagura** [comment]
Sounds good.

<b>For anyone else looking at this, I have published the project with up-to-date TypeScript definitions at [@srmagura/use-event-listener](https://www.npmjs.com/package/@srmagura/use-event-listener).</b>

**Comment by donavon** [comment]
deployed to npm as `@use-it/event-listener@0.1.4`
