### ISSUE TITLE
Republish the package with updated peerDependencies 'cause now we have a problem for React 17

### ISSUE THREAD

**Issue by tonix-tuft** [donavon/use-event-listener#39]
Hi! If you look at the current `package.json` of this package published on NPM:  https://unpkg.com/@use-it/event-listener@0.1.6/package.json

```json
{
  ...
  "peerDependencies": {
    "react": "^16.8.0"
  },
  ...
}
```

You will see that it only peer-depends on React ^16, whereas as React 17 is now released, it should be:

```json
{
  ...
  "peerDependencies": {
    "react": "^16.8.0 || ^17.0.0"
  },
  ...
}
```

With the current `package.json`, NPM returns the following error when I run `npm update`:

```
$ npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: bluelinks@5.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @use-it/event-listener@0.1.6
npm ERR! node_modules/@use-it/event-listener
npm ERR!   @use-it/event-listener@"^0.1.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/antony/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/antony/.npm/_logs/2021-02-26T09_51_18_073Z-debug.log
```

Could you publish the updated package.json file, please? Thank you!

**Comment by artursvonda** [comment]
Any update on this?

**Comment by tonix-tuft** [comment]
I am thinking about starting to use `yarn`...

**Comment by gregpurnell** [comment]
Looks like this was solved in PR #37  and merged into the `develop` branch. Are there any plans to deploy to `master` to get this fix in there? Thanks! @donavon

**Comment by edemaine** [comment]
With NPM 7, working around this requires `npm install --force`.

Perhaps it would make sense to just have a peer dependency of `>=16.8.0`? Then this issue will be fixed for the rest of time (until React breaks the package somehow 🙂 ).

**Comment by donavon** [comment]
published x0.1.7
