### ISSUE TITLE
Is useEffect necessary to update the ref? (genuine question)

### ISSUE THREAD

**Issue by zhouzi** [donavon/use-event-listener#9]
While reading the code, I realized the ref handler was updated differently from what I am used to. So I am genuinely wondering if there's some kind of best practice or performance implication I am missing.

Here's how the ref is currently updated:

```js
const useEventListener = (eventName, handler, element = global) => {
  const savedHandler = useRef();

  useEffect(() => {
    savedHandler.current = handler;
  }, [handler]);

  // The rest of the code goes here...
};
```

And here's how I usually update it:

```js
const useEventListener = (eventName, handler, element = global) => {
  const savedHandler = useRef();
  savedHandler.current = handler;

  // The rest of the code goes here...
};
```

From my understanding, references hold a mutable value that can be changed without triggering rerenders. They're really just "values floating around" so changing it this way has no side effects.

Are these two approaches equivalent? Thanks in advance! 🙏

**Comment by dviry** [comment]
my 2 cents: in second sample if props.handler ever changes your savedHandler.current will not ever get updated... I would not trust the "hold a mutable value", everything should be immutable in React ;)

**Comment by zhouzi** [comment]
> in second sample if props.handler ever changes your savedHandler.current will not ever get updated

The ref is updated every time the hook is called, regardless of whether `props.handler` changed or not. So compared to the example with `useEffect`, it's updated even more often. It shouldn't be an issue since updating a ref doesn't trigger a rerender.

> I would not trust the "hold a mutable value", everything should be immutable in React

I agree that mutability is a nightmare that should be avoided at all cost. But that's how React refs work: they hold a mutable value. I think it's ok to use them responsibly.

I'll close this issue, it was really just me being curious 😉
